#! /bin/bash
#Script to mass run tests


echo "Parser2 Test 1 run"
./comp1 tests/test1.prog output simulator/mytest1.asm

echo "Parser2 Test 2 run"
./comp1 tests/test2.prog output simulator/mytest2.asm

echo "Parser2 Test 3 run"
./comp1 tests/test3.prog output simulator/mytest3.asm

echo "Parser2 Test 4 run"
./comp1 tests/test4.prog output simulator/mytest4.asm

echo "Parser2 Test 5 run"
./comp1 tests/test5.prog output simulator/mytest5.asm

echo "Parser2 Test 6 run"
./comp1 tests/test6.prog output simulator/mytest6.asm

echo "Parser2 Test 7 run"
./comp1 tests/test7.prog output simulator/mytest7.asm

echo "Parser2 Test 8 run"
./comp1 tests/test8.prog output simulator/mytest8.asm

echo "Parser2 Test 9 run"
./comp1 tests/test9.prog output simulator/mytest9.asm
