#! /bin/bash
#Script to mass run tests

./parser1 tests/test1.prog output
echo "Test 1 run"
./parser1 tests/test2.errs output
echo "Test 2 run"
./parser1 tests/test3.errs output
echo "Test 3 run"
./parser1 tests/test4.errs output
echo "Test 4 run"
./parser1 tests/test5.errs output
echo "Test 5 run"
./parser1 tests/test6.errs output
echo "Test 6 run"
