#! /bin/bash
#Script to mass run tests


echo "Test 1 run"
./parser1 tests/test1.prog output

echo "Test 2 run"
./parser1 tests/test2.prog output

echo "Test 3 run"
./parser1 tests/test3.prog output

echo "Test 4 run"
./parser1 tests/test4.prog output

echo "Test 5 run"
./parser1 tests/test5.prog output

echo "Test 6 run"
./parser1 tests/test6.prog output

echo "Test 7 run"
./parser1 tests/test7.prog output

echo "Test 8 run"
./parser1 tests/test8.prog output

echo "Test 9 run"
./parser1 tests/test9.prog output
