#! /bin/bash
#Script to mass run tests


echo "ErrTest 1 run"
./comp1 tests/test1.errs output errs.asm
echo "ErrTest 2 run"
./comp1 tests/test2.errs output errs.asm
echo "ErrTest 3 run"
./comp1 tests/test3.errs output errs.asm
echo "ErrTest 4 run"
./comp1 tests/test4.errs output errs.asm
echo "ErrTest 5 run"
./comp1 tests/test5.errs output errs.asm
echo "ErrTest 6 run"
./comp1 tests/test6.errs output errs.asm
echo "ErrTest 7 run"

./comp1 tests/test7.errs output errs.asm
echo "ErrTest 8 run"

./comp1 tests/test8.errs output errs.asm
echo "ErrTest 9 run"

./comp1 tests/test9.errs output errs.asm
